language: ruby
cache: bundler
rvm:
- 2.1

notifications:
  email:
    on_success: change
    on_failure: change

script: bundle exec jekyll build --config=_config.yml,_config.development.yml --drafts && bundle exec htmlproof _site/
