language: ruby
rvm:
- 2.1

install: gem install jekyll html-proofer
script: jekyll build --config _config.yml,_config.local.yml && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer