# Site wide configuration

title:            Where do you want to throw today?
locale:           en_US
url:              //gusztavvargadr.github.io

# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Gusztáv Varga
  avatar: https://www.gravatar.com/avatar/6e455691ddfac67d6a8f0a17f06b5a8b?s=200
  bio: "Catch me if you can"
  email: me@gusztavvargadr.me
  disqus-shortname: wheredoyouwanttothrowtoday
  twitter: gusztavvargadr
  facebook: gusztav.varga.dr
  google:
    plus:
    analytics: UA-67541332-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gusztavvargadr
  stackoverflow: 119643/gusztav-varga-dr
  linkedin: gusztavvargadr
  xing:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
